### ISSUE TITLE
load() Callback Is Called Twice in IE10

### ISSUE THREAD

**Issue by bparmer** [raptorjs/raptor-loader#1]
When running in Internet Explorer 10, the `load(resources, callback)` function calls callback twice.

Looking at the `load()` function, there's 2 places that `done()` can be called:
1. In the listener function
2. If the `pendingCount` is 0 when load finishes

``` javascript
function load(resources, callback) {
    var errorMessages = [];
    var pendingCount = 0;

    function done() {
        if (errorMessages.length) {
            callback('Failed: ' + errorMessages.join(', '));
        } else {
            callback();
        }
    }

    function listener(err, url) {
        if (err) {
            errorMessages.push(url + ' (' + err + ')');
        }

        if (--pendingCount === 0) {
            done();
        }
    }

    function process(resourceType) {
        var resourcesForType = resources[resourceType];
        if (resourcesForType) {
            for (var i=0, len=resourcesForType.length; i<len; i++) {
                var url = resourcesForType[i];
                if (failed[url]) {
                    errorMessages.push(url + ' (' + failed[url] + ')');
                } else if (!completed[url]) {
                    pendingCount++;
                    emitter.once(url, listener);
                    start(resourceType, url);
                }
            }
        }
    }

    process('css');
    process('js');

    if (pendingCount === 0) {
        done();
    }
}
```

When running in IE 10, the `listener()` function is called _before_ `process('js')` returns, so the steps look something like this:
1. `process('js')` is called
2. `pendingCount` is increased to 1
3. The script is loaded via `headEl.appendChild(el)` in resource-loader.js
4. `listener()` is called, leading the pendingCount to decrement to 0 and `done()` to be called
5. `process('js')` returns
6. `pendingCount` is 0, so `done()` is called **again**

_Note that this only occurs once a script has been loaded and cached by IE10. The first time a script is loaded, it works fine, but subsequent attempts to load the script fail with this error._

**Comment by philidem** [comment]
Published lasso-loader@2.0.1
